export { default as About } from './about';
export { default as Cart } from './cart';
export { default as Home } from './home';
export { default as Login } from './login';
export { default as Main } from './main';
export { default as MyPage } from './mypage';
export { default as Product } from './product';
export { default as Signup } from './signup';
export { default as Checkout } from './checkout';
